#!/bin/bash

# Cleanup old lockfiles
rm -rf "${XDG_CONFIG_HOME}"/{BraveSoftware/Brave-Browser,gphotosdl/browser}/Singleton*

exec /usr/bin/brave-browser \
  --no-sandbox \
  --headless \
  --disable-dev-shm-usage \
  --disable-crash-reporter \
  --no-crashpad \
  --disable-blink-features \
  --disable-blink-features=AutomationControlled \
  --disable-translate \
  --disable-suggestions-service \
  --disable-save-password-bubble \
  --disable-session-crashed-bubble \
  --enable-unsafe-swiftshader \
  --no-first-run \
  "$@"